param([switch]$CheckOnly)
$ErrorActionPreference = 'Stop'
$projectPath = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
$appUrl = 'http://localhost:3000'
$mutex = New-Object Threading.Mutex($false, 'Local\FlashMapDesktopLauncher')
$ownsMutex = $false

function Test-FlashMap {
    try {
        $health = Invoke-RestMethod -Uri 'http://127.0.0.1:3000/api/health' -TimeoutSec 2
        return ($health.app -eq 'FlashMap' -and $health.mode -eq 'desktop' -and $health.version -eq 1)
    } catch { return $false }
}

try {
    $ownsMutex = $mutex.WaitOne(30000)
    if (-not $ownsMutex) { throw 'FlashMap startup is already in progress. Please try again shortly.' }
    if (-not (Test-FlashMap)) {
        # Do not replace or terminate an unrelated service occupying this port.
        $client = New-Object Net.Sockets.TcpClient
        try {
            $connected = $client.ConnectAsync('127.0.0.1', 3000)
            if ($connected.Wait(1000) -and $client.Connected) { throw 'Port 3000 is occupied by another application. Close that application and try again.' }
        } catch [AggregateException] { } finally { $client.Dispose() }
        $nodeCommand = Get-Command node.exe -ErrorAction SilentlyContinue
        if (-not $nodeCommand) { throw 'Node.js is missing. Install Node.js 22 or later and try again.' }
        if (-not (Test-Path -LiteralPath (Join-Path $projectPath 'dist\server.cjs'))) { throw 'Build FlashMap first: npm run build' }
        # No credential is included in arguments, browser URLs, or logs.
        $env:PORT = '3000'
        $process = Start-Process -FilePath $nodeCommand.Source -ArgumentList '"scripts\start.cjs"' -WorkingDirectory $projectPath -WindowStyle Hidden -PassThru
        $deadline = [DateTime]::UtcNow.AddSeconds(30)
        while (-not (Test-FlashMap)) {
            if ($process.HasExited -or [DateTime]::UtcNow -gt $deadline) { throw 'FlashMap could not start. Run npm start in the project to check installation.' }
            Start-Sleep -Milliseconds 300
        }
    }
    if ($CheckOnly) { Write-Output 'FlashMap desktop service is ready.'; return }
    $browserPaths = @(
        (Join-Path ${env:ProgramFiles(x86)} 'Microsoft\Edge\Application\msedge.exe'),
        (Join-Path $env:ProgramFiles 'Microsoft\Edge\Application\msedge.exe'),
        (Join-Path $env:ProgramFiles 'Google\Chrome\Application\chrome.exe'),
        (Join-Path $env:LOCALAPPDATA 'Google\Chrome\Application\chrome.exe')
    )
    $browser = $browserPaths | Where-Object { Test-Path -LiteralPath $_ } | Select-Object -First 1
    $privateBootstrap = Join-Path $env:LOCALAPPDATA 'FlashMap\desktop-import.html'
    $launchUrl = $appUrl
    if (Test-Path -LiteralPath $privateBootstrap) {
        # This authorization is randomly generated by FlashMap, never an AI key.
        # It is one-use and the application immediately removes it from the URL.
        $bootstrapText = [IO.File]::ReadAllText($privateBootstrap)
        $ticket = [regex]::Match($bootstrapText, 'name="ticket" value="([a-f0-9]{64})"').Groups[1].Value
        if (-not $ticket) { throw 'Private import authorization is unavailable.' }
        $launchUrl = "$appUrl/#desktop-import=$ticket"
    }
    if ($browser) { Start-Process -FilePath $browser -ArgumentList "--app=$launchUrl", '--new-window' -WindowStyle Normal }
    else { Start-Process $launchUrl -WindowStyle Normal }
} catch {
    if ($CheckOnly) { throw }
    Add-Type -AssemblyName PresentationFramework
    [Windows.MessageBox]::Show($_.Exception.Message, 'FlashMap', 'OK', 'Error') | Out-Null
} finally {
    if ($ownsMutex) { $mutex.ReleaseMutex() }
    $mutex.Dispose()
}
